[0m22:04:19.591657 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe37553a7b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe374e0b4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe3746ffb10>]}


============================== 22:04:19.595679 | a2790bcd-70ba-4ef3-924e-7f22cffa53de ==============================
[0m22:04:19.595679 [info ] [MainThread]: Running with dbt=1.10.13
[0m22:04:19.596190 [debug] [MainThread]: running dbt with arguments {'static_parser': 'True', 'no_print': 'None', 'send_anonymous_usage_stats': 'True', 'write_json': 'True', 'log_cache_events': 'False', 'printer_width': '80', 'indirect_selection': 'eager', 'partial_parse': 'True', 'warn_error': 'None', 'use_colors': 'True', 'version_check': 'True', 'fail_fast': 'False', 'profiles_dir': '/home/bafbi/.dbt', 'cache_selected_only': 'False', 'target_path': 'None', 'quiet': 'False', 'use_experimental_parser': 'False', 'log_format': 'default', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_path': 'logs', 'empty': 'None', 'invocation_command': 'dbt test --profiles-dir /home/bafbi/.dbt', 'debug': 'False'}
[0m22:04:19.596621 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/bafbi/school/m2/bi/projet-m2-bi/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:04:19.597399 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.06281834, "process_in_blocks": "1232", "process_kernel_time": 0.137429, "process_mem_max_rss": "100912", "process_out_blocks": "16", "process_user_time": 0.992609}
[0m22:04:19.597786 [debug] [MainThread]: Command `dbt test` failed at 22:04:19.597705 after 0.06 seconds
[0m22:04:19.598078 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe3747e3a80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe374815c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe374715f20>]}
[0m22:04:19.598369 [debug] [MainThread]: Flushing usage events
[0m22:04:20.054430 [debug] [MainThread]: An error was encountered while trying to flush usage events
